### ISSUE TITLE
Unable to use SpidermiR

### ISSUE THREAD

**Issue by cloudred20** [claudiacava/SpidermiR#1]
Hi,

I'm trying to use SpidermiR. No matter whatever command I type in console I get the following error.
Error in .DownloadURL(site) : Not Found (HTTP 404).

Can you provide an explanation?

**Comment by claudiacava** [comment]
Dear,
SpidermiR uses the site http://genemania.org/data/ to download network
data, and now there is a problem with that site.

I think soon the mantainer of GeneMANIA will adjust it




2017-01-30 8:27 GMT+01:00 megha20 <notifications@github.com>:

**Comment by aambioinfo** [comment]
Hello,
same problem here. 
http://genemania.org/data/ seems to contain no data.
Any idea when this will be modified?

Thank you.

**Comment by claudiacava** [comment]
Now it works

2017-02-07 9:50 GMT+01:00 aambioinfo <notifications@github.com>:

**Comment by aambioinfo** [comment]
Great. Thank you!
