### ISSUE TITLE
Unable to use the package: error 403

### ISSUE THREAD

**Issue by laurentpays** [claudiacava/SpidermiR#2]
Hi, when I try to run the code:    org<-SpidermiRquery_species(species)

I get the following error:   Error in .DownloadURL(site) : Forbidden (HTTP 403).

Any idea on how to solve this?

Thanks in advance
Laurent

**Comment by claudiacava** [comment]
Dear Laurent, 
SpidermiR uses the site http://genemania.org/data/ to download network data, and now there is a problem with that site. As Soon as possible I think the mantainer of GeneMANIA will adjust it.
Otherwise I will find a solution as soon as possible.

Best

**Comment by claudiacava** [comment]
now it works. 

Best

**Comment by laurentpays** [comment]
Thanks
